name: Build and push multicluster scheduler

on:
  push:
  workflow_dispatch:

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Build Docker image
        working-directory: multi-cluster-scheduler
        run: docker build -t moule3053/multi-cluster-scheduler .

      - name: Login to Dockerhub
        uses: docker/login-action@v1
        with:
          registry: docker.io
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_ROBOT_TOKEN }}

      - name: Push Docker images
        run: docker push moule3053/multi-cluster-scheduler